/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/orders/display": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** GET /api/orders/display */
    get: operations["get_display_orders"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/orders/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** GET /api/orders/{id} */
    get: operations["get_order_details"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/staff/flavors/config": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** GET /api/staff/flavors/config */
    get: operations["get_flavor_configs"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/staff/flavors/{flavor}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** PUT /api/staff/flavors/{flavor} */
    put: operations["set_flavor_config"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/staff/orders": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** GET /api/staff/orders */
    get: operations["get_staff_orders"];
    put?: never;
    /** POST /api/staff/orders */
    post: operations["create_order"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/staff/orders/{id}/cancel": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** POST /api/staff/orders/{id}/cancel */
    post: operations["cancel_order"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/staff/orders/{id}/complete": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** POST /api/staff/orders/{id}/complete */
    post: operations["complete_order"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/staff/orders/{id}/notification": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** PUT /api/orders/{id}/notification */
    put: operations["add_notification"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/staff/orders/{id}/priority": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** PUT /api/staff/orders/{id}/priority */
    put: operations["update_order_priority"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/staff/production": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** POST /api/staff/production */
    post: operations["update_production"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/staff/stock": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** GET /api/staff/stock */
    get: operations["get_stock"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/wait-times": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** GET /api/wait-times */
    get: operations["get_wait_times"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/line_callback": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["line_callback"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    CreateOrderRequest: {
      isPriority?: boolean | null;
      items: components["schemas"]["Item"][];
    };
    DisplayOrder: {
      displayNumber: string;
      /** Format: int32 */
      id: number;
    };
    DisplayOrdersResponse: {
      cooking: components["schemas"]["DisplayOrder"][];
      ready: components["schemas"]["DisplayOrder"][];
      waiting: components["schemas"]["DisplayOrder"][];
    };
    /** @enum {string} */
    Flavor: "tsubuan" | "custard" | "kurikinton";
    FlavorConfig: {
      /** Format: int32 */
      cookingTimeMinutes: number;
      /** Format: int32 */
      quantityPerBatch: number;
    };
    FlavorConfigsResponse: {
      custard: components["schemas"]["FlavorConfig"];
      kurikinton: components["schemas"]["FlavorConfig"];
      tsubuan: components["schemas"]["FlavorConfig"];
    };
    Item: {
      flavor: components["schemas"]["Flavor"];
      quantity: number;
    };
    Notify:
      | {
          Discord: {
            /** Format: int64 */
            channel_id: number;
            /** Format: int64 */
            user_id: number;
          };
        }
      | {
          Line: {
            user_id: string;
          };
        };
    NotifyRequest:
      | {
          Discord: {
            /** Format: int64 */
            channel_id: number;
            /** Format: int64 */
            user_id: number;
          };
        }
      | {
          Line: {
            user_id: string;
          };
        };
    OrderDetailsResponse: {
      displayNumber: string;
      /** Format: int64 */
      estimatedWaitMinutes?: number | null;
      /** Format: int32 */
      id: number;
      items: components["schemas"]["Item"][];
      /** Format: date-time */
      orderedAt: string;
      status: components["schemas"]["OrderStatus"];
    };
    /** @enum {string} */
    OrderStatus: "waiting" | "cooking" | "ready" | "completed" | "cancelled";
    StaffOrderResponse: {
      /** Format: date-time */
      completedAt?: string | null;
      displayNumber: string;
      /** Format: int32 */
      id: number;
      isPriority: boolean;
      items: components["schemas"]["Item"][];
      /** Format: date-time */
      orderedAt: string;
      /** Format: date-time */
      readyAt?: string | null;
      status: components["schemas"]["OrderStatus"];
    };
    StockResponse: {
      custard: number;
      kurikinton: number;
      tsubuan: number;
    };
    UpdateOrderPriorityRequest: {
      isPriority: boolean;
    };
    UpdateProductionRequest: {
      items: components["schemas"]["Item"][];
    };
    UpdateProductionResponse: {
      newlyReadyOrders: number[];
      unallocatedItems: components["schemas"]["Item"][];
    };
    WaitTimeResponse: {
      waitTimes: components["schemas"]["WaitTimes"];
    };
    WaitTimes: {
      /** Format: int64 */
      custard?: number | null;
      /** Format: int64 */
      kurikinton?: number | null;
      /** Format: int64 */
      tsubuan?: number | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  get_display_orders: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Orders grouped for display */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DisplayOrdersResponse"];
        };
      };
      /** @description Failed to load display orders */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_order_details: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Order id */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Order details */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OrderDetailsResponse"];
        };
      };
      /** @description Order not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Failed to load order details */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_flavor_configs: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Flavor configs */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FlavorConfigsResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Failed to load flavor configs */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  set_flavor_config: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Flavor */
        flavor: components["schemas"]["Flavor"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["FlavorConfig"];
      };
    };
    responses: {
      /** @description Flavor config updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Failed to save flavor config */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_staff_orders: {
    parameters: {
      query?: {
        /** @description Comma-separated order statuses */
        status?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Staff order list */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StaffOrderResponse"][];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Failed to load orders */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  create_order: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateOrderRequest"];
      };
    };
    responses: {
      /** @description Created order */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StaffOrderResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Failed to save order */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  cancel_order: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Order id */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Cancelled order */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StaffOrderResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Order not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Failed to save cancelled order */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  complete_order: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Order id */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Completed order */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StaffOrderResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Order not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Failed to save completed order */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  add_notification: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Order id */
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["NotifyRequest"];
      };
    };
    responses: {
      /** @description Updated order notification */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StaffOrderResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Order not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Failed to save notification update */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  update_order_priority: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Order id */
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateOrderPriorityRequest"];
      };
    };
    responses: {
      /** @description Updated order */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StaffOrderResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Order not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Failed to save order priority update */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  update_production: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateProductionRequest"];
      };
    };
    responses: {
      /** @description Production update result */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UpdateProductionResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Failed to save production update */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_stock: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Unallocated stock by flavor */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StockResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Failed to load stock */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_wait_times: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current wait times */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WaitTimeResponse"];
        };
      };
      /** @description Failed to load wait times */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  line_callback: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": string;
      };
    };
    responses: {
      /** @description Webhook accepted */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid webhook body */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid LINE signature */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
